name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: djw8605/doc-ci-scripts@master

    # Use Derek's action
    - name: Verify Links
      uses: djw8605/linkchecker-action@master
      with:
        site-dir: /github/workspace/site

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
